### ISSUE TITLE
Bug report: effects

### ISSUE THREAD

**Issue by HeartcraftSmp** [Rapha149/VoidTotem#1]
In the "Potion effects to apply after resurrection" section of the config I couldn't add any more than like 3 more effects than the default. Just wondering if you know why?

**Comment by Rapha149** [comment]
Can you send me the config with more than 3 added effects and the server log when you tried it out?

**Comment by HeartcraftSmp** [comment]
https://paste.shockbyte.com/karokuguvakoqowixeme
This is an outdated version though, I'll update now

**Comment by HeartcraftSmp** [comment]
https://paste.shockbyte.com/fufikidadeneweguyuso

**Comment by HeartcraftSmp** [comment]
Wait
Fixed
Sorry

**Comment by Rapha149** [comment]
Ok 🙂
